var-name = [ "VIKASH-1","VIKASH-2","VIKASH-3","VIKASH-4","VIKASH-5" ]
application_name= "vikash"
account_id = 3931876
policy_name = null
runbook_url = null
incident_preference = "PER_POLICY"
apdex_warning_threshold = 0.8
error_rate_duration = 300
apdex_critical_threshold = 0.7
apdex_duration = 300
apdex_t = 0.4
error_rate_warning_threshold = 2
error_rate_critical_threshold = 5